# CONSTANTES

SMOOTHMOVE = {
    "VERYSMOOTH": 4,
    "SMOOTH": 2,
    "NORMAL": 1,
    "NOTSMOOTH": 0.5,
    "NOTSMOOTHATALL": 0.25
    }

# PARAMETRES
GENERAL_SETTINGS = {
    "REPEAT_ACTION_DELAI": 200,
    "SMOOTHLESSMODE": SMOOTHMOVE["VERYSMOOTH"]
    }
